### ISSUE TITLE
toolbar crash after joomla 3.1.5 upgrade

### ISSUE THREAD

**Issue by igifx** [kyleledbetter/apptheme#4]
Hello, after latest joomla update toolbar style is totaly crashed.
Best regards

**Comment by kyleledbetter** [comment]
For some reason they changed from Bootstrap markup to non-Bootstrap markup for the Joomla admin in 3.1.5...
You'll need to edit /administrator/templates/apptheme-admin/css/template.css and add:

``` css
.btn-toolbar .btn-wrapper {
display: inline-block;
margin: 0 0 5px 5px;
}
```

I'll get that added in the next update
